-- Expand LoyaltyProgram enum
ALTER TYPE "LoyaltyProgram" ADD VALUE IF NOT EXISTS 'AZUL';
ALTER TYPE "LoyaltyProgram" ADD VALUE IF NOT EXISTS 'IBERIA';
ALTER TYPE "LoyaltyProgram" ADD VALUE IF NOT EXISTS 'AA';
ALTER TYPE "LoyaltyProgram" ADD VALUE IF NOT EXISTS 'TAP';
ALTER TYPE "LoyaltyProgram" ADD VALUE IF NOT EXISTS 'FLYING_BLUE';

-- Add summary rate fields for new programs
ALTER TABLE "settings"
ADD COLUMN IF NOT EXISTS "azulRateCents" INTEGER NOT NULL DEFAULT 1700,
ADD COLUMN IF NOT EXISTS "iberiaRateCents" INTEGER NOT NULL DEFAULT 1700,
ADD COLUMN IF NOT EXISTS "aaRateCents" INTEGER NOT NULL DEFAULT 1700,
ADD COLUMN IF NOT EXISTS "tapRateCents" INTEGER NOT NULL DEFAULT 1700,
ADD COLUMN IF NOT EXISTS "flyingBlueRateCents" INTEGER NOT NULL DEFAULT 1700;
